### ДЗ по Numpy

1. Импортируйте библиотеку numpy, переименовав ее на np

In [211]:
import numpy as np

2. Выведите на печать версию numpy и ее конфигурацию

In [212]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

3. Создайте нулевой вектор размера 10

In [213]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Как создать вектор размера 10, пятый элемент которого = 1

In [214]:
vector = np.random.randint(10, size=10)
print(vector)
vector[4] = 1
vector

[9 4 7 5 1 9 3 7 8 4]


array([9, 4, 7, 5, 1, 9, 3, 7, 8, 4])

5. Создайте вектор со значениями от 10 до 49

In [215]:
vector = np.random.randint(10, 50, size=10)
vector

array([21, 28, 15, 22, 29, 22, 45, 19, 31, 16])

6. Инвертировать вектор (первый элемент становится последним)

In [216]:
vector = np.random.randint(10, size=10)
vector_invert = vector[::-1]
vector, vector_invert

(array([1, 4, 2, 6, 3, 2, 5, 3, 7, 3]), array([3, 7, 3, 5, 2, 3, 6, 2, 4, 1]))

7. Создайте матрицу 3x3 со значениями от 0 до 8

In [217]:
matrix = np.random.randint(9, size=(3, 3))
matrix

array([[4, 6, 8],
       [4, 8, 5],
       [4, 0, 8]])

8. Найдите индексы ненулевых элементов из вектора [1,2,0,0,4,0]

In [218]:
vector = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(vector)

(array([0, 1, 4]),)

9. Создайте единичную матрицу 3x3

In [219]:
matrix_eye = np.eye(3)
matrix_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

10. Создайте массив 3 на 3 на 3 со случайными значениями

In [220]:
matrix_rand = np.random.randint(10, size=(3,3,3))
matrix_rand

array([[[1, 4, 0],
        [7, 3, 3],
        [4, 2, 2]],

       [[7, 5, 7],
        [4, 2, 0],
        [8, 9, 1]],

       [[9, 8, 0],
        [4, 8, 7],
        [6, 4, 3]]])

11. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения



In [221]:
matrix = np.random.randint(100, size=(10,10))
minimum = matrix.min()
maximum = matrix.max()
matrix, minimum, maximum

(array([[50,  2, 24, 13, 82, 14, 61, 89, 66, 28],
        [12, 87,  4, 37, 27, 66,  4, 90, 27, 75],
        [54, 98,  2, 67, 30, 22, 79, 59, 70,  9],
        [ 2, 97, 39, 52, 68, 31,  1, 27, 34, 95],
        [86, 95, 68,  7,  1, 31,  8, 95, 26, 10],
        [84,  0, 26, 60,  2, 20, 77, 67, 71, 20],
        [37,  2, 97, 15, 15, 25, 47, 51, 34, 22],
        [89, 25, 65, 30, 93, 47, 58, 31, 18, 35],
        [90, 11, 86, 77, 99, 96,  4, 78, 28, 86],
        [35, 66, 73, 31, 47,  2, 32, 43, 57, 54]]),
 0,
 99)

12. Создайте случайный вектор размером 30 и найдите среднее значение

In [222]:
vector = np.random.randint(100, size=30)
mean = vector.mean()
vector, mean

(array([70, 50, 58, 99, 35, 74, 48, 13, 89, 96, 41, 15, 27, 69, 51, 95, 70,
        29, 25, 18, 53, 20, 56, 44, 47, 93, 22, 46, 49, 87]),
 52.96666666666667)

2. Создайте двумерный-массив с 1(единицами) на границе и 0(нулями) внутри

In [223]:
matrix = np.ones((10,10))
matrix[1:-1, 1:-1] = 0
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

3. Умножьте матрицу 5x3 на матрицу 3x2 (матричное произведение)

In [224]:
a = np.random.randint(10, size=(5,3))
b = np.random.randint(10, size=(3,2))
mul_a_b = np.matmul(a, b)
a, b, mul_a_b

(array([[3, 2, 7],
        [9, 5, 1],
        [3, 7, 4],
        [8, 5, 3],
        [2, 6, 6]]),
 array([[6, 0],
        [1, 9],
        [2, 6]]),
 array([[34, 60],
        [61, 51],
        [33, 87],
        [59, 63],
        [30, 90]]))

4. Как вычислить ((A + B) * (- A / 2)) на месте (без копирования - то есть без создания дополнительного массива кроме существующих A, B)?

In [225]:
a = np.random.random(size=2)
b = np.random.random(size=2)
print (a, b)
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
a

[0.60458309 0.5852662 ] [0.38540992 0.37567011]


array([-0.29926652, -0.28120177])

5. Как получить документацию по функции numpy add (сложение) из командной строки?

In [226]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Создайте случайный вектор размером 10 и отсортируйте его

In [227]:
vector = np.random.randint(100, size=10)
print(vector)
vector.sort()
vector

[88 77 70 61 19 90 71 76 12 74]


array([12, 19, 61, 70, 71, 74, 76, 77, 88, 90])

7. Как суммировать  массив размером 10

In [228]:
array = np.random.randint(10, size=10)
print(array)
np.sum(array)

[3 9 2 6 5 1 7 8 8 9]


58

8. Рассмотрим два случайных массива A и B, проверьте, равны ли они

In [229]:
a = np.random.randint(2, size=2)
b = np.random.randint(2, size=2)
print (a, b)
np.array_equal(a, b)

[0 0] [0 1]


False

9. Создайте случайный вектор размером 10 и замените максимальное значение на 0

In [230]:
vector = np.random.randint(10, size=10)
print(vector)
vector[vector.argmax()] = 0
vector

[5 8 7 4 6 2 7 6 9 4]


array([5, 8, 7, 4, 6, 2, 7, 6, 0, 4])